---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-json
          - id: check-added-large-files
            args: ['--maxkb=50000']
          - id: end-of-file-fixer
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: requirements-txt-fixer
          - id: check-case-conflict
          - id: pretty-format-json
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [--format, parsable]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        - id: isort
          name: isort (python)
    - repo: https://github.com/lovesegfault/beautysh
      rev: v6.2.1
      hooks:
          - id: beautysh
    - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
          - id: dockerfilelint
            stages: [commit]
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.35.0
      hooks:
          - id: commitizen
            stages: [commit-msg]